// European (UEFA) domestic leagues we care about: first tier ("main") and
// second tier ("B"). Third tier and below are deliberately absent — see
// TIER3_PLUS_PATTERNS in leagues.js for the safety net that catches anything
// that slips through with an unexpected slug.
//
// `slug` is the Flashscore URL path segment (the part after /soccer/<country>/).
// Slugs occasionally change when a league is renamed or re-sponsored; anything
// that fails to match is reported in the "needs review" section of the report
// rather than being silently dropped.

export const UEFA_COUNTRIES = new Set([
  'albania', 'andorra', 'armenia', 'austria', 'azerbaijan', 'belarus', 'belgium',
  'bosnia-and-herzegovina', 'bulgaria', 'croatia', 'cyprus', 'czech-republic',
  'denmark', 'england', 'estonia', 'faroe-islands', 'finland', 'france',
  'georgia', 'germany', 'gibraltar', 'greece', 'hungary', 'iceland', 'ireland',
  'israel', 'italy', 'kazakhstan', 'kosovo', 'latvia', 'liechtenstein',
  'lithuania', 'luxembourg', 'malta', 'moldova', 'montenegro', 'netherlands',
  'north-macedonia', 'northern-ireland', 'norway', 'poland', 'portugal',
  'romania', 'russia', 'san-marino', 'scotland', 'serbia', 'slovakia',
  'slovenia', 'spain', 'sweden', 'switzerland', 'turkey', 'ukraine', 'wales',
]);

/** @type {{country: string, slug: string, name: string, tier: 1|2, gender: 'M'|'W'}[]} */
export const LEAGUES = [
  // --- Big five -------------------------------------------------------------
  { country: 'england', slug: 'premier-league', name: 'Premier League', tier: 1, gender: 'M' },
  { country: 'england', slug: 'championship', name: 'Championship', tier: 2, gender: 'M' },
  { country: 'england', slug: 'wsl', name: 'Women’s Super League', tier: 1, gender: 'W' },
  { country: 'england', slug: 'womens-championship', name: 'Women’s Championship', tier: 2, gender: 'W' },
  { country: 'spain', slug: 'laliga', name: 'LaLiga', tier: 1, gender: 'M' },
  { country: 'spain', slug: 'laliga2', name: 'LaLiga 2', tier: 2, gender: 'M' },
  { country: 'spain', slug: 'liga-f', name: 'Liga F', tier: 1, gender: 'W' },
  { country: 'germany', slug: 'bundesliga', name: 'Bundesliga', tier: 1, gender: 'M' },
  { country: 'germany', slug: '2-bundesliga', name: '2. Bundesliga', tier: 2, gender: 'M' },
  { country: 'germany', slug: 'frauen-bundesliga', name: 'Frauen-Bundesliga', tier: 1, gender: 'W' },
  { country: 'italy', slug: 'serie-a', name: 'Serie A', tier: 1, gender: 'M' },
  { country: 'italy', slug: 'serie-b', name: 'Serie B', tier: 2, gender: 'M' },
  { country: 'italy', slug: 'serie-a-women', name: 'Serie A Women', tier: 1, gender: 'W' },
  { country: 'france', slug: 'ligue-1', name: 'Ligue 1', tier: 1, gender: 'M' },
  { country: 'france', slug: 'ligue-2', name: 'Ligue 2', tier: 2, gender: 'M' },
  { country: 'france', slug: 'premiere-ligue', name: 'Première Ligue', tier: 1, gender: 'W' },

  // --- Rest of western Europe ----------------------------------------------
  { country: 'netherlands', slug: 'eredivisie', name: 'Eredivisie', tier: 1, gender: 'M' },
  { country: 'netherlands', slug: 'eerste-divisie', name: 'Eerste Divisie', tier: 2, gender: 'M' },
  { country: 'netherlands', slug: 'eredivisie-women', name: 'Eredivisie Women', tier: 1, gender: 'W' },
  { country: 'portugal', slug: 'liga-portugal', name: 'Liga Portugal', tier: 1, gender: 'M' },
  { country: 'portugal', slug: 'liga-portugal-2', name: 'Liga Portugal 2', tier: 2, gender: 'M' },
  { country: 'portugal', slug: 'liga-bpi', name: 'Liga BPI', tier: 1, gender: 'W' },
  { country: 'belgium', slug: 'jupiler-pro-league', name: 'Jupiler Pro League', tier: 1, gender: 'M' },
  { country: 'belgium', slug: 'challenger-pro-league', name: 'Challenger Pro League', tier: 2, gender: 'M' },
  { country: 'belgium', slug: 'super-league-women', name: 'Super League Women', tier: 1, gender: 'W' },
  { country: 'scotland', slug: 'premiership', name: 'Premiership', tier: 1, gender: 'M' },
  { country: 'scotland', slug: 'championship', name: 'Championship', tier: 2, gender: 'M' },
  { country: 'scotland', slug: 'swpl-1', name: 'SWPL 1', tier: 1, gender: 'W' },
  { country: 'ireland', slug: 'premier-division', name: 'Premier Division', tier: 1, gender: 'M' },
  { country: 'ireland', slug: 'first-division', name: 'First Division', tier: 2, gender: 'M' },
  { country: 'northern-ireland', slug: 'premiership', name: 'NIFL Premiership', tier: 1, gender: 'M' },
  { country: 'northern-ireland', slug: 'championship', name: 'NIFL Championship', tier: 2, gender: 'M' },
  { country: 'northern-ireland', slug: 'premiership-women', name: 'NIFL Premiership Women', tier: 1, gender: 'W' },
  { country: 'wales', slug: 'cymru-premier', name: 'Cymru Premier', tier: 1, gender: 'M' },
  { country: 'switzerland', slug: 'super-league', name: 'Super League', tier: 1, gender: 'M' },
  { country: 'switzerland', slug: 'challenge-league', name: 'Challenge League', tier: 2, gender: 'M' },
  { country: 'switzerland', slug: 'super-league-women', name: 'Women’s Super League', tier: 1, gender: 'W' },
  { country: 'austria', slug: 'bundesliga', name: 'Bundesliga', tier: 1, gender: 'M' },
  { country: 'austria', slug: '2-liga', name: '2. Liga', tier: 2, gender: 'M' },
  { country: 'austria', slug: 'frauen-bundesliga', name: 'Frauen-Bundesliga', tier: 1, gender: 'W' },
  { country: 'luxembourg', slug: 'national-division', name: 'National Division', tier: 1, gender: 'M' },
  { country: 'malta', slug: 'premier-league', name: 'Premier League', tier: 1, gender: 'M' },
  { country: 'malta', slug: 'challenge-league', name: 'Challenge League', tier: 2, gender: 'M' },
  { country: 'gibraltar', slug: 'national-league', name: 'National League', tier: 1, gender: 'M' },
  { country: 'andorra', slug: 'primera-divisio', name: 'Primera Divisió', tier: 1, gender: 'M' },
  { country: 'san-marino', slug: 'campionato', name: 'Campionato Sammarinese', tier: 1, gender: 'M' },

  // --- Nordics (in season through the European summer) ----------------------
  { country: 'sweden', slug: 'allsvenskan', name: 'Allsvenskan', tier: 1, gender: 'M' },
  { country: 'sweden', slug: 'superettan', name: 'Superettan', tier: 2, gender: 'M' },
  { country: 'sweden', slug: 'damallsvenskan', name: 'Damallsvenskan', tier: 1, gender: 'W' },
  { country: 'sweden', slug: 'elitettan', name: 'Elitettan', tier: 2, gender: 'W' },
  { country: 'norway', slug: 'eliteserien', name: 'Eliteserien', tier: 1, gender: 'M' },
  { country: 'norway', slug: 'obos-ligaen', name: 'OBOS-ligaen', tier: 2, gender: 'M' },
  { country: 'norway', slug: 'toppserien', name: 'Toppserien', tier: 1, gender: 'W' },
  { country: 'denmark', slug: 'superliga', name: 'Superliga', tier: 1, gender: 'M' },
  { country: 'denmark', slug: '1st-division', name: '1st Division', tier: 2, gender: 'M' },
  { country: 'denmark', slug: 'kvindeligaen', name: 'Kvindeligaen', tier: 1, gender: 'W' },
  { country: 'finland', slug: 'veikkausliiga', name: 'Veikkausliiga', tier: 1, gender: 'M' },
  { country: 'finland', slug: 'ykkosliiga', name: 'Ykkösliiga', tier: 2, gender: 'M' },
  { country: 'finland', slug: 'kansallinen-liiga', name: 'Kansallinen Liiga', tier: 1, gender: 'W' },
  { country: 'iceland', slug: 'besta-deild-karla', name: 'Besta deild karla', tier: 1, gender: 'M' },
  { country: 'iceland', slug: '1-deild', name: '1. deild', tier: 2, gender: 'M' },
  { country: 'iceland', slug: 'besta-deild-women', name: 'Besta deild kvenna', tier: 1, gender: 'W' },
  { country: 'faroe-islands', slug: 'premier-league', name: 'Betri deildin', tier: 1, gender: 'M' },
  { country: 'faroe-islands', slug: '1-deild', name: '1. deild', tier: 2, gender: 'M' },

  // --- Central & eastern Europe --------------------------------------------
  { country: 'poland', slug: 'ekstraklasa', name: 'Ekstraklasa', tier: 1, gender: 'M' },
  { country: 'poland', slug: 'division-1', name: 'I liga', tier: 2, gender: 'M' },
  { country: 'poland', slug: 'ekstraliga-women', name: 'Ekstraliga Women', tier: 1, gender: 'W' },
  { country: 'czech-republic', slug: '1-liga', name: 'Chance Liga', tier: 1, gender: 'M' },
  { country: 'czech-republic', slug: '2-liga', name: 'FNL', tier: 2, gender: 'M' },
  { country: 'slovakia', slug: 'nike-liga', name: 'Niké liga', tier: 1, gender: 'M' },
  { country: 'slovakia', slug: '2-liga', name: '2. liga', tier: 2, gender: 'M' },
  { country: 'hungary', slug: 'nb-i', name: 'NB I', tier: 1, gender: 'M' },
  { country: 'hungary', slug: 'nb-ii', name: 'NB II', tier: 2, gender: 'M' },
  { country: 'romania', slug: 'superliga', name: 'SuperLiga', tier: 1, gender: 'M' },
  { country: 'romania', slug: 'liga-2', name: 'Liga 2', tier: 2, gender: 'M' },
  { country: 'bulgaria', slug: 'efbet-league', name: 'efbet League', tier: 1, gender: 'M' },
  { country: 'bulgaria', slug: 'vtora-liga', name: 'Vtora liga', tier: 2, gender: 'M' },
  { country: 'croatia', slug: 'hnl', name: 'HNL', tier: 1, gender: 'M' },
  { country: 'croatia', slug: 'prva-nl', name: 'Prva NL', tier: 2, gender: 'M' },
  { country: 'serbia', slug: 'super-liga', name: 'Super liga', tier: 1, gender: 'M' },
  { country: 'serbia', slug: 'prva-liga', name: 'Prva liga', tier: 2, gender: 'M' },
  { country: 'slovenia', slug: 'prva-liga', name: 'Prva liga', tier: 1, gender: 'M' },
  { country: 'slovenia', slug: '2-snl', name: '2. SNL', tier: 2, gender: 'M' },
  { country: 'bosnia-and-herzegovina', slug: 'premier-league', name: 'Premijer liga', tier: 1, gender: 'M' },
  { country: 'north-macedonia', slug: 'prva-liga', name: 'Prva liga', tier: 1, gender: 'M' },
  { country: 'albania', slug: 'superliga', name: 'Kategoria Superiore', tier: 1, gender: 'M' },
  { country: 'montenegro', slug: 'prva-liga', name: 'Prva liga', tier: 1, gender: 'M' },
  { country: 'kosovo', slug: 'superliga', name: 'Superliga', tier: 1, gender: 'M' },
  { country: 'greece', slug: 'super-league', name: 'Super League', tier: 1, gender: 'M' },
  { country: 'greece', slug: 'super-league-2', name: 'Super League 2', tier: 2, gender: 'M' },
  { country: 'cyprus', slug: 'first-division', name: 'First Division', tier: 1, gender: 'M' },
  { country: 'cyprus', slug: 'second-division', name: 'Second Division', tier: 2, gender: 'M' },
  { country: 'turkey', slug: 'super-lig', name: 'Süper Lig', tier: 1, gender: 'M' },
  { country: 'turkey', slug: '1-lig', name: '1. Lig', tier: 2, gender: 'M' },
  { country: 'turkey', slug: 'super-lig-women', name: 'Kadınlar Süper Ligi', tier: 1, gender: 'W' },
  { country: 'israel', slug: 'ligat-haal', name: 'Ligat ha’Al', tier: 1, gender: 'M' },
  { country: 'israel', slug: 'liga-leumit', name: 'Liga Leumit', tier: 2, gender: 'M' },

  // --- Baltics, CIS & Caucasus ---------------------------------------------
  { country: 'russia', slug: 'premier-league', name: 'Premier League', tier: 1, gender: 'M' },
  { country: 'russia', slug: 'first-league', name: 'First League', tier: 2, gender: 'M' },
  { country: 'russia', slug: 'supreme-division-women', name: 'Supreme Division Women', tier: 1, gender: 'W' },
  { country: 'ukraine', slug: 'premier-league', name: 'Premier League', tier: 1, gender: 'M' },
  { country: 'ukraine', slug: 'persha-liga', name: 'Persha Liha', tier: 2, gender: 'M' },
  { country: 'belarus', slug: 'vysshaya-liga', name: 'Vysshaya Liga', tier: 1, gender: 'M' },
  { country: 'belarus', slug: 'pershaya-liga', name: 'Pershaya Liga', tier: 2, gender: 'M' },
  { country: 'belarus', slug: 'vysshaya-liga-women', name: 'Vysshaya Liga Women', tier: 1, gender: 'W' },
  { country: 'estonia', slug: 'meistriliiga', name: 'Meistriliiga', tier: 1, gender: 'M' },
  { country: 'estonia', slug: 'esiliiga', name: 'Esiliiga', tier: 2, gender: 'M' },
  { country: 'latvia', slug: 'virsliga', name: 'Virsliga', tier: 1, gender: 'M' },
  { country: 'latvia', slug: '1-liga', name: '1. liga', tier: 2, gender: 'M' },
  { country: 'lithuania', slug: 'toplyga', name: 'TOPLYGA', tier: 1, gender: 'M' },
  { country: 'lithuania', slug: 'i-lyga', name: 'I Lyga', tier: 2, gender: 'M' },
  { country: 'georgia', slug: 'erovnuli-liga', name: 'Erovnuli Liga', tier: 1, gender: 'M' },
  { country: 'georgia', slug: 'erovnuli-liga-2', name: 'Erovnuli Liga 2', tier: 2, gender: 'M' },
  { country: 'armenia', slug: 'premier-league', name: 'Premier League', tier: 1, gender: 'M' },
  { country: 'armenia', slug: 'first-league', name: 'First League', tier: 2, gender: 'M' },
  { country: 'azerbaijan', slug: 'premyer-liqa', name: 'Premyer Liqa', tier: 1, gender: 'M' },
  { country: 'azerbaijan', slug: 'birinci-divizion', name: 'Birinci Divizion', tier: 2, gender: 'M' },
  { country: 'kazakhstan', slug: 'premier-league', name: 'Premier League', tier: 1, gender: 'M' },
  { country: 'kazakhstan', slug: 'first-division', name: 'First Division', tier: 2, gender: 'M' },
  { country: 'kazakhstan', slug: 'league-women', name: 'Kazakhstan League Women', tier: 1, gender: 'W' },
  { country: 'moldova', slug: 'super-liga', name: 'Super Liga', tier: 1, gender: 'M' },
  { country: 'moldova', slug: 'liga-1', name: 'Liga 1', tier: 2, gender: 'M' },
];

export const LEAGUE_INDEX = new Map(
  LEAGUES.map((l) => [`${l.country}/${l.slug}`, l]),
);
